

services:
 eurekaserver:
   build: ./eurekaserver
   container_name: eurekaserver
   ports:
     - "8761:8761"
   networks:
     - microservices-net


 produk-service:
   build: ./produk-service
   container_name: produk-service
   ports:
     - "8081:8081"
   environment:
     - spring.datasource.url=jdbc:mysql://mysql:3306/dbcommerce_produk?useSSL=false&serverTimezone=UTC
     - spring.datasource.username=root
     - spring.datasource.password=root_password
     - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
   depends_on:
     - eurekaserver
     - mysql
   networks:
     - microservices-net


 order:
   build: ./order
   container_name: order
   ports:
     - "8083:8083"
   environment:
     - spring.datasource.url=jdbc:mysql://mysql:3306/dbcommerce_orders?useSSL=false&serverTimezone=UTC
     - spring.datasource.username=root
     - spring.datasource.password=root_password
     - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
   depends_on:
     - eurekaserver
     - mysql
   networks:
     - microservices-net


 payment-service:
   build: ./payment-service
   container_name: payment-service
   ports:
     - "8082:8082"
   environment:
     - spring.datasource.url=jdbc:mysql://mysql:3306/dbcommerce_payments?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true


     - spring.datasource.username=root
     - spring.datasource.password=root_password
     - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
   depends_on:
     - eurekaserver
   networks:
     - microservices-net


 customer-service:
   build: ./customer-service
   container_name: customer-service
   ports:
     - "8084:8084"
   environment:
     - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
   depends_on:
     - eurekaserver
     - mysql
   networks:
     - microservices-net


 api-gateway:
   build: ./api-gateway
   container_name: api-gateway
   ports:
     - "8080:8080"
   environment:
     - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
   depends_on:
     - eurekaserver
   networks:
     - microservices-net


 rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq
   ports:
     - "5672:5672"
     - "15672:15672"
   networks:
     - microservices-net


 mysql:
   image: mysql:8.0
   container_name: mysql
   environment:
     MYSQL_ROOT_PASSWORD: root_password
   volumes:
     - ./mysql/init:/docker-entrypoint-initdb.d  # Mount script ke direktori init
   ports:
     - "3306:3306"
   networks:
     - microservices-net


 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   environment:
     PMA_HOST: mysql  # Nama service MySQL di Docker Compose
     PMA_PORT: 3306
     PMA_USER: root
     PMA_PASSWORD: root_password
   ports:
     - "8085:80"  # Akses phpMyAdmin via port 8085
   networks:
     - microservices-net
   depends_on:
     - mysql


networks:
 microservices-net:
   driver: bridge








