apiVersion: v1
kind: Service
metadata:
  name: produk-service
spec:
  selector:
    app: produk-service
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP


File order-service-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: yourrepo/order-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: spring.application.name
          value: "order-service"
        - name: eureka.client.service-url.defaultZone
          value: "http://eurekaserver:8761/eureka/"
        - name: spring.datasource.url
          value: "jdbc:mysql://mysql:3306/dbcommerce_orders?useSSL=false&serverTimezone=UTC"
        - name: spring.datasource.username
          value: "root"
        - name: spring.datasource.password
          value: "root_password"


